/**
 * Offline backfill driver: turn a `simulate()` plan into queued actions.
 *
 * The barrier (`lastForegroundAt`) is the safety rail. It is written on every
 * foreground, and backfill only ever fabricates events after it — so reopening
 * the app twice in a row cannot invent the same window twice, and nothing is
 * ever inserted behind messages the user has already read.
 *
 * Skeleton-first: this function returns as soon as the actions are queued. The
 * bodies are generated by the ordinary scheduler drain, so unread badges and
 * conversation previews appear immediately rather than waiting on the network.
 */
import { enqueue } from './scheduler';
import { simulate, type SimInput, type SimPlan } from './simulate';
import { repo } from '../db/repo';

const BARRIER_KEY = 'lastForegroundAt';

/** Read the barrier. Returns undefined on a first-ever launch. */
export async function getBarrier(): Promise<number | undefined> {
  return repo.getSetting<number>(BARRIER_KEY);
}

export async function setBarrier(now: number): Promise<void> {
  await repo.putSetting(BARRIER_KEY, now);
}

/**
 * Plan and queue everything that "happened" while the app was closed, then move
 * the barrier forward.
 *
 * @param now current wall clock, injected for testability
 * @returns the plan that was queued (empty on a first launch or a short absence)
 */
export async function runBackfill(
  now: number,
  input: SimInput,
  seed = 'backfill',
): Promise<SimPlan> {
  const barrier = await getBarrier();

  // First launch: there is no "while you were away" yet. Just set the barrier —
  // inventing history for an app the user has never opened would be nonsense.
  if (barrier == null) {
    await setBarrier(now);
    return { events: [], from: now, to: now, truncated: false };
  }

  const plan = simulate(barrier, now, input, seed);
  for (const ev of plan.events) {
    await enqueue({
      kind: ev.kind,
      fireAt: ev.at,
      // `at` rides along in the payload so the handler stamps the message with
      // the time it was supposed to arrive, not the time the queue drained it.
      // Reactions carry their post; DM sessions carry the pair — the payload
      // shapes the live handlers already read (M-I5).
      payload: {
        contactId: ev.contactId,
        convId: ev.convId,
        at: ev.at,
        ...(ev.momentId ? { momentId: ev.momentId } : {}),
        ...(ev.dm ? { a: ev.dm.a, b: ev.dm.b, groupId: ev.dm.groupId, fireAt: ev.at } : {}),
        // Kind-specific fields (gift envelope, 聚会 phase, 拉群 roster) —
        // exactly the shapes the live handlers already read (M-I18).
        ...(ev.payload ?? {}),
      },
      now,
      // A planned kind that the live foreground pass ALSO owns carries that
      // path's stable id, or the `actionExists` guard three lines later would
      // not recognise it and the same gift/聚会/拉群 would be queued twice.
      id: ev.id ?? `bf_${ev.kind}_${ev.contactId}_${ev.at}`,
    });
  }

  // Advance the barrier to the end of the simulated window, not to `now` — the
  // SETTLE_MARGIN tail stays unclaimed so the next run can cover it.
  await setBarrier(plan.to);
  return plan;
}
