/**
 * Generated pictures → the runtime media library (M-J3).
 *
 * The transport lives in src/llm/image.ts; this is the business half every
 * caller shares: run one generation, land the bytes as a normal media row,
 * hand back an `idb:` ref — or return null and let the caller fall back to
 * the asset pool. NEVER throws: a broken generation endpoint costs a picture,
 * not a conversation, and no error from here ever reaches the screen.
 *
 * The `import('../llm/image')` is DYNAMIC on purpose: the startup bundle sits
 * a few KB under its ratchet, and a module only needed when a generation
 * actually fires has no business in the cold-start chunk.
 */
import { repo } from '../db/repo';
import type { MediaItemVM } from '../data/types';
import { registerMediaMeta, materializeMedia } from '../data/media-registry';
import type { NsfwTier } from '../llm/router';
import { logError } from '../lib/errlog';

/**
 * Land generated bytes in the runtime media library and hand back the `idb:`
 * ref messages/moments store. The default `kind: 'generated'` keeps them out
 * of the random photo pool (a generated 饼干 must not resurface later as a
 * random 晚霞) while the media page can still list and delete them; the row
 * rides the normal media store, so it backs up and restores like any import.
 *
 * `now` is caller-injected (rule #4 — handlers run inside the one
 * time-evolution path and may be materializing the past); `seed` keeps two
 * same-millisecond generations from colliding, deterministically.
 */
export async function putGeneratedMedia(
  blob: Blob,
  mime: string,
  opts: { now: number; seed: string; tags?: string[]; kind?: MediaItemVM['kind'] },
): Promise<string> {
  const id = `gen_${opts.now.toString(36)}_${fnv(opts.seed)}`;
  const item: MediaItemVM = {
    id,
    kind: opts.kind ?? 'generated',
    tags: opts.tags ?? [],
    mime,
    blob,
    createdAt: opts.now,
  };
  await repo.putMedia(item);
  // Register + materialize immediately: the message referencing this ref
  // renders in the very next frame, and a placeholder flash there reads as a
  // broken send rather than as lazy loading.
  registerMediaMeta(id, { kind: item.kind, tags: item.tags });
  materializeMedia(id, blob);
  return `idb:${id}`;
}

export interface GenerateToLibraryOptions {
  prompt: string;
  /** Tier of the surface the prompt derives from — see src/lib/nsfw-tier.ts. */
  tier: NsfwTier;
  now: number;
  seed: string;
  tags?: string[];
  kind?: MediaItemVM['kind'];
  size?: string;
  timeoutMs?: number;
}

/**
 * One generation, end to end: readiness gate (config + key + 铁律 6 tier
 * check) → generate → media library → ref. Null on ANY failure or when
 * generation simply isn't configured — the graceful-fallback contract every
 * calling surface (chat photo, Moments 配图, avatar swap) is built on.
 */
export async function generateToLibrary(opts: GenerateToLibraryOptions): Promise<string | null> {
  try {
    const img = await import('../llm/image');
    // The tier gate lives inside isImageGenReady too, so a full-tier surface
    // with only a mainland endpoint configured answers "not ready" and the
    // caller falls back to the pool — no call, no bytes, no log noise.
    if (!(await img.isImageGenReady(opts.tier))) return null;
    const { blob, mime } = await img.generateImage(opts.prompt, opts.tier, {
      size: opts.size,
      timeoutMs: opts.timeoutMs,
    });
    return await putGeneratedMedia(blob, mime, opts);
  } catch (e) {
    // Failure is a diagnostic event, never a visible one (photo-send contract:
    // degrade to the pool / to words, don't break the bubble).
    logError('image.generate', e);
    return null;
  }
}

/** FNV-1a hex — deterministic id suffix (rule #4: no Math.random in this path). */
function fnv(s: string): string {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return (h >>> 0).toString(16);
}
