/**
 * The life a persona is having when you are not talking to her (M-E3).
 *
 * Until now an agent had a persona card, a daily mood, and nothing else: every
 * conversation started from the same standing state, forever. Ask "最近怎么样"
 * on day 1 and on day 200 and you get answers drawn from the same empty well,
 * because there is no well — nothing happens to her between messages.
 *
 * This module gives each agent a slow-moving life: a few concurrent arcs (work,
 * family, health, a project, a friendship) that advance through stages over
 * weeks, plus a weekly agenda of when she is busy. Two properties make it
 * affordable and safe:
 *
 *  - **Zero LLM.** Arcs are generated by seeded pure functions from the persona
 *    card. They cost nothing per tick and add one short line to the prompt.
 *  - **Zero storage, fully replayable.** `lifelineAt(persona, t)` is a pure
 *    function of (contactId, t). There is no state to drift, offline backfill
 *    reproduces it exactly, and constitution rule #4 holds.
 *
 * What the agent must NOT do is narrate the arc unprompted every message. The
 * directive says "this is true of your life right now" — background, not script.
 */
import type { PersonaVM } from '../data/types';
import { seededRng } from '../lib/money';

const DAY = 86_400_000;

/* ==================================================================== */
/* Arc definitions                                                       */
/* ==================================================================== */

export type ArcDomain = 'work' | 'family' | 'health' | 'project' | 'social';

interface ArcTemplate {
  domain: ArcDomain;
  /** Stages in order. The arc walks them; the last one loops back to a new arc. */
  stages: string[];
  /** Typical days per stage; the actual value is jittered per arc. */
  stageDays: number;
  /** How strongly being in this arc colours the mood (0..1). */
  weight: number;
}

/**
 * Deliberately mundane. An agent whose life is a series of dramatic events
 * reads as a soap opera; the texture that makes someone feel real is a deadline
 * that keeps slipping and a relative who keeps calling.
 */
const ARC_TEMPLATES: ArcTemplate[] = [
  {
    domain: 'work',
    stages: [
      '手上接了个新活儿，还在摸情况',
      '项目进入赶工期，最近加班有点多',
      '交付前后事最杂，人有点绷着',
      '终于交出去了，松了口气',
    ],
    stageDays: 9,
    weight: 0.8,
  },
  {
    domain: 'project',
    stages: [
      '开始折腾一个自己的小东西',
      '做到一半卡住了，有点烦',
      '想通了关键的一步，来劲了',
      '做完了，但没什么人看，情绪复杂',
    ],
    stageDays: 12,
    weight: 0.6,
  },
  {
    domain: 'family',
    stages: [
      '家里最近总打电话来问近况',
      '被催了点什么事，懒得细说',
      '和家里聊开了一点',
      '这阵子家里安静下来了',
    ],
    stageDays: 11,
    weight: 0.7,
  },
  {
    domain: 'health',
    stages: [
      '最近作息乱了，老是睡不够',
      '有点小毛病，去看了一下',
      '开始逼自己早点睡、动一动',
      '状态明显好起来了',
    ],
    stageDays: 8,
    weight: 0.5,
  },
  {
    domain: 'social',
    stages: [
      '认识了个还聊得来的新朋友',
      '和某个老朋友有点淡了',
      '被拉去参加了个不太想去的局',
      '最近更想一个人待着',
    ],
    stageDays: 10,
    weight: 0.4,
  },
];

export interface ArcState {
  domain: ArcDomain;
  /** The current stage's one-line description. */
  stage: string;
  stageIndex: number;
  /** 0..1 through the current stage. */
  progress: number;
  weight: number;
  /** When this arc started (ms). Stable for a given (contactId, arc slot). */
  startedAt: number;
}

/** How many arcs run concurrently. Two is enough texture without a soap opera. */
export const CONCURRENT_ARCS = 2;

/**
 * The arcs a persona is living through at `t`. Pure: same inputs, same output,
 * forever — which is what lets offline backfill and the live app agree.
 *
 * `epoch` anchors the walk. It is the persona's own start, not the app's, so a
 * contact added today does not begin mid-arc as if it had a past it never had.
 */
export function lifelineAt(
  persona: Pick<PersonaVM, 'contactId'>,
  t: number,
  epoch: number,
): ArcState[] {
  const out: ArcState[] = [];
  for (let slot = 0; slot < CONCURRENT_ARCS; slot++) {
    out.push(arcForSlot(persona.contactId, slot, t, epoch));
  }
  return out;
}

/**
 * One slot's arc. A slot cycles: pick a template, walk its stages, then pick
 * the next template (never the same one twice running — that reads as a loop).
 */
function arcForSlot(contactId: string, slot: number, t: number, epoch: number): ArcState {
  const elapsed = Math.max(0, t - epoch);
  let cursor = 0;
  let cycle = 0;
  let previous = -1;

  // Walk forward cycle by cycle. Bounded by construction: each cycle is at
  // least 4 × 5 days, so even a decade resolves in a few hundred iterations.
  for (;;) {
    const rng = seededRng(`arc:${contactId}:${slot}:${cycle}`);
    // Never the same template twice in a row for this slot.
    const pool = ARC_TEMPLATES.filter((_, i) => i !== previous);
    const pickIndex = Math.floor(rng() * pool.length);
    const template = pool[pickIndex];
    previous = ARC_TEMPLATES.indexOf(template);

    // Each stage gets its own jittered length: ±40% around the template's.
    const lengths = template.stages.map((_, i) => {
      const j = seededRng(`arclen:${contactId}:${slot}:${cycle}:${i}`)();
      return Math.round(template.stageDays * (0.6 + 0.8 * j) * DAY);
    });
    const total = lengths.reduce((a, b) => a + b, 0);

    if (cursor + total > elapsed || cycle > 500) {
      let within = elapsed - cursor;
      for (let i = 0; i < lengths.length; i++) {
        if (within < lengths[i] || i === lengths.length - 1) {
          return {
            domain: template.domain,
            stage: template.stages[i],
            stageIndex: i,
            progress: lengths[i] > 0 ? clamp01(within / lengths[i]) : 0,
            weight: template.weight,
            startedAt: epoch + cursor,
          };
        }
        within -= lengths[i];
      }
    }
    cursor += total;
    cycle++;
  }
}

/**
 * The prompt line. One sentence per arc, capped — this rides in the SCENE layer
 * after everything else (constitution: the six-layer order is fixed, new content
 * only appends), and the token budget for the tail is small on purpose.
 */
export function lifelineDirective(arcs: ArcState[]): string {
  if (arcs.length === 0) return '';
  const lines = arcs.slice(0, CONCURRENT_ARCS).map((a) => `- ${a.stage}`);
  return [
    '【你最近的状态】',
    ...lines,
    '这些是背景，不是话题清单——别主动汇报，只有聊到了才自然带出来。',
  ].join('\n');
}

/* ==================================================================== */
/* Agenda: when she is genuinely unavailable                             */
/* ==================================================================== */

export interface Busy {
  busy: boolean;
  /** Why, for the prompt when she replies late. Empty when free. */
  reason: string;
}

const BUSY_REASONS = ['在开会', '在赶deadline', '在外面办事', '在陪家里人', '在健身房', '在补觉'];

/**
 * Is she busy at `t`?
 *
 * `activeHours` already answers "is she awake". This answers the finer question
 * "is she available", which is what makes a delayed reply readable as a life
 * rather than as lag. Seeded on a 2-hour bucket so a busy block has a real
 * duration instead of flickering minute to minute.
 */
export function agendaAt(
  persona: Pick<PersonaVM, 'contactId'>,
  t: number,
  arcs: ArcState[] = [],
): Busy {
  const bucket = Math.floor(t / (2 * 3_600_000));
  const rng = seededRng(`agenda:${persona.contactId}:${bucket}`);
  // A work arc in its crunch stage makes her measurably harder to reach — the
  // arc is not merely narrated, it changes behaviour.
  const crunch = arcs.some((a) => a.domain === 'work' && a.stageIndex === 1);
  const chance = crunch ? 0.3 : 0.12;
  if (rng() >= chance) return { busy: false, reason: '' };
  const reason = BUSY_REASONS[Math.floor(rng() * BUSY_REASONS.length)];
  return { busy: true, reason };
}

/* ==================================================================== */

function clamp01(n: number): number {
  return Math.min(1, Math.max(0, Number.isFinite(n) ? n : 0));
}
