import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * M-J3 图片生成 — transport, tier gate, media landing, and wiring guards.
 *
 * image.ts is the SECOND module in the repo that talks to the network directly
 * (after llm/http), which is exactly why every guarantee here is a red-flip
 * test rather than a review note:
 *   1. unconfigured → typed error, ZERO network attempts;
 *   2. 铁律 6: a full-tier prompt never reaches a preset (SiliconFlow is a
 *      mainland official endpoint!) — only a user-declared capable custom one;
 *   3. b64 preferred, url re-fetched into a blob before the CDN link dies;
 *   4. generated bytes land as `kind: 'generated'` media rows, OUT of the
 *      random photo pool;
 *   5. every calling surface degrades to the old pool path on any failure;
 *   6. each generation is a counted paid call.
 */

/* ------------------------------------------------------------------ */
/* Module mocks: settings/media rows + keystore, in-memory             */
/* ------------------------------------------------------------------ */

const settings = new Map<string, unknown>();
const secrets = new Map<string, string>();
const media = new Map<string, Record<string, unknown>>();

// Passthrough mock (asr.test.ts precedent): replacing the module WHOLESALE
// would drop its non-repo exports and break the module graph elsewhere.
vi.mock('../../src/db/repo', async (importOriginal) => ({
  ...(await importOriginal<typeof import('../../src/db/repo')>()),
  repo: {
    getSetting: async (k: string) => settings.get(k),
    putSetting: async (k: string, v: unknown) => {
      settings.set(k, v);
    },
    putMedia: async (item: { id: string }) => {
      media.set(item.id, item as unknown as Record<string, unknown>);
    },
    getMediaItem: async (id: string) => media.get(id),
    getProviders: async () => [],
    // 朋友权限 (M-J7): this fake exists to test image generation, not audience
    // rules — no restrictions is the honest answer here, not an oversight.
    getFriendPerms: async () => ({}),
  },
}));

vi.mock('../../src/lib/keystore', () => ({
  getSecret: async (alias: string) => secrets.get(alias) ?? null,
  hasSecret: (alias: string) => secrets.has(alias),
  setSecret: async (alias: string, v: string) => {
    secrets.set(alias, v);
  },
  deleteSecret: (alias: string) => {
    secrets.delete(alias);
  },
}));

// vi.hoisted, unlike the asr.test precedent: this file's import graph reaches
// @capacitor/core EAGERLY (moments-service → …engine → llm/service imports the
// Capacitor symbol at module scope), so the mock factory runs before a plain
// top-level const would exist.
const { bridgeRequest } = vi.hoisted(() => ({
  bridgeRequest: vi.fn(() => new Promise<never>(() => {})),
}));
vi.mock('@capacitor/core', () => ({
  CapacitorHttp: { request: bridgeRequest },
  Capacitor: { isNativePlatform: () => false },
}));

import {
  IMAGE_PRESETS,
  IMAGE_SETTING,
  imagePresetToConfig,
  getImageProvider,
  saveImageProvider,
  imageAllowedAtTier,
  isImageGenReady,
  generateImage,
  fetchImageBlob,
  type ImageProviderVM,
} from '../../src/llm/image';
import { putGeneratedMedia, generateToLibrary } from '../../src/ai/gen-media';
import { resolvePhotoOrGenerate, resetPhotoMemory, hasPoolMaterial } from '../../src/ai/photo-send';
import {
  registerMediaMeta,
  unregisterMedia,
  photoPoolIds,
  listRegisteredMedia,
} from '../../src/data/media-registry';
import { shouldSwapAvatar, maybeAvatarSwap, AVATAR_SWAP_RATE, type MomentsHooks } from '../../src/ai/moments-service';
import { makePersona } from '../../src/data/persona-defaults';
import type { Bubble } from '../../src/llm/types';
import type { ContactVM, MomentVM } from '../../src/data/types';

const realFetch = globalThis.fetch;

/** A 1x1 transparent PNG, base64 — enough bytes to be a real blob. */
const PNG_B64 =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==';

const CFG_SF: ImageProviderVM = {
  kind: 'siliconflow',
  label: 'SiliconFlow',
  baseUrl: 'https://img.example.test/v1',
  keyAlias: 'key_img_siliconflow',
  model: 'Kwai-Kolors/Kolors',
  sizes: ['1024x1024', '512x512'],
};

const CFG_CUSTOM: ImageProviderVM = {
  kind: 'custom',
  label: '自定义',
  baseUrl: 'https://gw.example.test/v1',
  keyAlias: 'key_img_custom',
  model: 'flux-dev',
  sizes: ['1024x1024'],
};

function okJson(body: unknown): Response {
  return {
    ok: true,
    status: 200,
    text: async () => JSON.stringify(body),
    blob: async () => new Blob([Uint8Array.from(atob(PNG_B64), (c) => c.charCodeAt(0))], { type: 'image/png' }),
  } as unknown as Response;
}

beforeEach(() => {
  settings.clear();
  secrets.clear();
  media.clear();
  resetPhotoMemory();
  bridgeRequest.mockReset();
  bridgeRequest.mockImplementation(() => new Promise<never>(() => {}));
  // The registry is module state — clear anything a previous case registered.
  for (const m of listRegisteredMedia()) unregisterMedia(m.id);
});

afterEach(() => {
  globalThis.fetch = realFetch;
  vi.restoreAllMocks();
});

/* ------------------------------------------------------------------ */
/* Presets & config                                                    */
/* ------------------------------------------------------------------ */

describe('presets and config persistence', () => {
  it('ships SiliconFlow first-class with the Kolors default, all https', () => {
    const sf = IMAGE_PRESETS.siliconflow;
    expect(sf.baseUrl).toBe('https://api.siliconflow.cn/v1');
    expect(sf.model).toBe('Kwai-Kolors/Kolors');
    for (const p of Object.values(IMAGE_PRESETS)) {
      expect(p.baseUrl.startsWith('https://')).toBe(true);
      expect(p.sizes.length).toBeGreaterThan(0);
    }
  });

  it('imagePresetToConfig: keyAlias per kind, never a key (rule #2); unknown → custom', () => {
    const c = imagePresetToConfig('siliconflow');
    expect(c.keyAlias).toBe('key_img_siliconflow');
    expect(JSON.stringify(c)).not.toMatch(/sk-/);
    expect(imagePresetToConfig('nope').kind).toBe('custom');
  });

  it('save → get roundtrip; malformed rows read as "not configured"', async () => {
    expect(await getImageProvider()).toBeNull();
    await saveImageProvider(CFG_SF);
    expect(await getImageProvider()).toEqual(CFG_SF);
    settings.set(IMAGE_SETTING, { garbage: true });
    expect(await getImageProvider()).toBeNull();
  });
});

/* ------------------------------------------------------------------ */
/* 铁律 6 tier gate                                                    */
/* ------------------------------------------------------------------ */

describe('铁律 6：full 档只放行用户显式声明的 custom 端点', () => {
  it('imageAllowedAtTier truth table — SiliconFlow 是国内官方，全开档无条件出局', () => {
    expect(imageAllowedAtTier(CFG_SF, 'off')).toBe(true);
    expect(imageAllowedAtTier(CFG_SF, 'ambiguous')).toBe(true);
    expect(imageAllowedAtTier(CFG_SF, 'full')).toBe(false);
    // 预设勾了也没用（字段只对 custom 有意义）。
    expect(imageAllowedAtTier({ ...CFG_SF, nsfwCapable: true }, 'full')).toBe(false);
    expect(imageAllowedAtTier({ kind: 'openai', nsfwCapable: true }, 'full')).toBe(false);
    // custom：未声明即 NO，声明了才放行。
    expect(imageAllowedAtTier(CFG_CUSTOM, 'full')).toBe(false);
    expect(imageAllowedAtTier({ ...CFG_CUSTOM, nsfwCapable: true }, 'full')).toBe(true);
  });

  it('generateImage refuses full-tier on SiliconFlow BEFORE any network I/O', async () => {
    await saveImageProvider(CFG_SF);
    secrets.set(CFG_SF.keyAlias, 'k');
    const fetchSpy = vi.fn();
    globalThis.fetch = fetchSpy as unknown as typeof fetch;
    await expect(generateImage('全开档提示词', 'full')).rejects.toMatchObject({
      name: 'ImageGenError',
      kind: 'tier_blocked',
    });
    expect(fetchSpy).not.toHaveBeenCalled();
    expect(bridgeRequest).not.toHaveBeenCalled();
  });

  it('a declared custom endpoint passes the gate (and off-tier passes everywhere)', async () => {
    await saveImageProvider({ ...CFG_CUSTOM, nsfwCapable: true });
    secrets.set(CFG_CUSTOM.keyAlias, 'k');
    globalThis.fetch = vi.fn(async () => okJson({ data: [{ b64_json: PNG_B64 }] })) as unknown as typeof fetch;
    const r = await generateImage('x', 'full');
    expect(r.blob.size).toBeGreaterThan(0);
  });

  it('isImageGenReady folds the tier gate in — full+siliconflow answers "not ready"', async () => {
    await saveImageProvider(CFG_SF);
    secrets.set(CFG_SF.keyAlias, 'k');
    expect(await isImageGenReady('off')).toBe(true);
    expect(await isImageGenReady('full')).toBe(false);
    secrets.delete(CFG_SF.keyAlias);
    expect(await isImageGenReady('off')).toBe(false); // alias ≠ key
  });
});

/* ------------------------------------------------------------------ */
/* Transport                                                           */
/* ------------------------------------------------------------------ */

describe('generation transport', () => {
  it('unconfigured → typed error, zero network', async () => {
    const fetchSpy = vi.fn();
    globalThis.fetch = fetchSpy as unknown as typeof fetch;
    await expect(generateImage('x', 'off')).rejects.toMatchObject({ kind: 'not_configured' });
    expect(fetchSpy).not.toHaveBeenCalled();
  });

  it('siliconflow body speaks its native dialect (image_size/batch_size)', async () => {
    await saveImageProvider(CFG_SF);
    secrets.set(CFG_SF.keyAlias, 'k');
    let sent: Record<string, unknown> = {};
    globalThis.fetch = vi.fn(async (_u: string, init: { body: string }) => {
      sent = JSON.parse(init.body);
      return okJson({ images: [{ b64_json: PNG_B64 }] });
    }) as unknown as typeof fetch;
    await generateImage('一只猫', 'off', { size: '512x512' });
    expect(sent.image_size).toBe('512x512');
    expect(sent.batch_size).toBe(1);
    expect(sent.size).toBeUndefined();
  });

  it('openai/custom body speaks OpenAI (size/n/response_format), url hits /images/generations', async () => {
    await saveImageProvider(CFG_CUSTOM);
    secrets.set(CFG_CUSTOM.keyAlias, 'k');
    let url = '';
    let sent: Record<string, unknown> = {};
    globalThis.fetch = vi.fn(async (u: string, init: { body: string }) => {
      url = String(u);
      sent = JSON.parse(init.body);
      return okJson({ data: [{ b64_json: PNG_B64 }] });
    }) as unknown as typeof fetch;
    await generateImage('x', 'off');
    expect(url).toBe('https://gw.example.test/v1/images/generations');
    expect(sent.size).toBe('1024x1024');
    expect(sent.n).toBe(1);
    expect(sent.response_format).toBe('b64_json');
  });

  it('b64_json preferred; url-only answers are re-fetched into a blob', async () => {
    await saveImageProvider(CFG_SF);
    secrets.set(CFG_SF.keyAlias, 'k');
    const calls: string[] = [];
    globalThis.fetch = vi.fn(async (u: string) => {
      calls.push(String(u));
      if (String(u).includes('/images/generations')) {
        return okJson({ images: [{ url: 'https://cdn.example.test/out.png' }] });
      }
      return okJson({});
    }) as unknown as typeof fetch;
    const r = await generateImage('x', 'off');
    expect(calls).toHaveLength(2);
    expect(calls[1]).toBe('https://cdn.example.test/out.png');
    expect(r.mime).toBe('image/png');
    expect(r.blob.size).toBeGreaterThan(0);
  });

  it('auth/ratelimit/server statuses map to typed kinds', async () => {
    await saveImageProvider(CFG_SF);
    secrets.set(CFG_SF.keyAlias, 'k');
    for (const [status, kind] of [
      [401, 'auth'],
      [429, 'rate_limit'],
      [500, 'server'],
    ] as const) {
      globalThis.fetch = vi.fn(async () =>
        ({ ok: false, status, text: async () => '{}' }) as unknown as Response,
      ) as unknown as typeof fetch;
      await expect(generateImage('x', 'off')).rejects.toMatchObject({ kind });
    }
  });

  it('a hanging endpoint rejects with timeout around the deadline, never awaits forever', async () => {
    await saveImageProvider(CFG_SF);
    secrets.set(CFG_SF.keyAlias, 'k');
    globalThis.fetch = vi.fn(
      (_u: unknown, init?: { signal?: AbortSignal }) =>
        new Promise((_res, rej) => {
          init?.signal?.addEventListener('abort', () => rej(new Error('aborted')));
        }),
    ) as unknown as typeof fetch;
    const t0 = Date.now();
    await expect(generateImage('x', 'off', { timeoutMs: 120 })).rejects.toMatchObject({
      kind: 'timeout',
    });
    expect(Date.now() - t0).toBeLessThan(2_000);
  });

  it('url download rides the bridge fallback with a REJECTING deadline (constitution trap)', async () => {
    // fetch fails → bridge hangs → raceDeadline must reject, boundedly.
    (globalThis as { Capacitor?: unknown }).Capacitor = { isNativePlatform: () => true };
    globalThis.fetch = vi.fn(async () => {
      throw new Error('no cors');
    }) as unknown as typeof fetch;
    try {
      await expect(
        fetchImageBlob('https://cdn.example.test/out.png', 150),
      ).rejects.toMatchObject({ name: 'ImageGenError' });
      expect(bridgeRequest).toHaveBeenCalledTimes(1);
    } finally {
      delete (globalThis as { Capacitor?: unknown }).Capacitor;
    }
  });

  it('every generation is a counted paid call (usage kind "image")', async () => {
    await saveImageProvider(CFG_SF);
    secrets.set(CFG_SF.keyAlias, 'k');
    globalThis.fetch = vi.fn(async () => okJson({ data: [{ b64_json: PNG_B64 }] })) as unknown as typeof fetch;
    await generateImage('x', 'off');
    await new Promise((r) => setTimeout(r, 10)); // recordUsage is fire-and-forget
    const rows = settings.get('usage:daily') as Array<{ counts: Record<string, number> }>;
    expect(rows?.[0]?.counts.image).toBe(1);
  });
});

/* ------------------------------------------------------------------ */
/* Media landing                                                       */
/* ------------------------------------------------------------------ */

describe('generated bytes land in the media library', () => {
  it('putGeneratedMedia writes a kind:"generated" row, registers it, returns an idb: ref', async () => {
    const blob = new Blob([new Uint8Array([1, 2, 3])], { type: 'image/png' });
    const ref = await putGeneratedMedia(blob, 'image/png', { now: 1_754_600_000_000, seed: 's1', tags: ['吃'] });
    expect(ref.startsWith('idb:gen_')).toBe(true);
    const id = ref.slice(4);
    expect(media.get(id)).toMatchObject({ kind: 'generated', tags: ['吃'], mime: 'image/png' });
    // Registered so the very next frame can draw it.
    expect(listRegisteredMedia('generated').some((m) => m.id === id)).toBe(true);
    // Deterministic id: same (now, seed) → same ref (rule #4, no Math.random).
    const ref2 = await putGeneratedMedia(blob, 'image/png', { now: 1_754_600_000_000, seed: 's1' });
    expect(ref2).toBe(ref);
  });

  it('generated items never enter the random photo pool', async () => {
    await putGeneratedMedia(new Blob(['x']), 'image/png', { now: 1, seed: 'a', tags: ['风景'] });
    expect(photoPoolIds()).toEqual([]);
    expect(photoPoolIds(['风景'], true)).toEqual([]);
  });

  it('generateToLibrary: not configured → null with zero network; failure → null, never a throw', async () => {
    const fetchSpy = vi.fn();
    globalThis.fetch = fetchSpy as unknown as typeof fetch;
    expect(await generateToLibrary({ prompt: 'x', tier: 'off', now: 1, seed: 's' })).toBeNull();
    expect(fetchSpy).not.toHaveBeenCalled();

    await saveImageProvider(CFG_SF);
    secrets.set(CFG_SF.keyAlias, 'k');
    globalThis.fetch = vi.fn(async () => {
      throw new Error('boom');
    }) as unknown as typeof fetch;
    expect(await generateToLibrary({ prompt: 'x', tier: 'off', now: 1, seed: 's' })).toBeNull();
  });

  it('generateToLibrary success: ref lands, tier gate still folded in', async () => {
    await saveImageProvider(CFG_SF);
    secrets.set(CFG_SF.keyAlias, 'k');
    globalThis.fetch = vi.fn(async () => okJson({ data: [{ b64_json: PNG_B64 }] })) as unknown as typeof fetch;
    const ref = await generateToLibrary({ prompt: 'x', tier: 'off', now: 2, seed: 's' });
    expect(ref?.startsWith('idb:gen_')).toBe(true);
    // full tier + mainland preset: silently null, zero calls.
    const spy = vi.fn();
    globalThis.fetch = spy as unknown as typeof fetch;
    expect(await generateToLibrary({ prompt: 'x', tier: 'full', now: 3, seed: 's' })).toBeNull();
    expect(spy).not.toHaveBeenCalled();
  });
});

/* ------------------------------------------------------------------ */
/* Outlet 1: chat photo bubble                                         */
/* ------------------------------------------------------------------ */

describe('resolvePhotoOrGenerate: pool first, generation second, old path always last', () => {
  const persona = { contactId: 'ai_a', imageTags: ['美食'] };
  const bubble: Bubble = { type: 'image', content: '刚烤的饼干' };

  it('a real tagged pool hit wins — no generation even when configured', async () => {
    registerMediaMeta('lib1', { kind: 'photo', tags: ['美食'] });
    await saveImageProvider(CFG_SF);
    secrets.set(CFG_SF.keyAlias, 'k');
    const fetchSpy = vi.fn();
    globalThis.fetch = fetchSpy as unknown as typeof fetch;
    const r = await resolvePhotoOrGenerate(bubble, persona, 'c1', 'seed', 'off', 1_754_600_000_000);
    expect(r?.ref).toBe('idb:lib1');
    expect(fetchSpy).not.toHaveBeenCalled();
  });

  it('no real material + configured → generates, remembers, keeps the caption', async () => {
    expect(hasPoolMaterial(persona.imageTags)).toBe(false);
    await saveImageProvider(CFG_SF);
    secrets.set(CFG_SF.keyAlias, 'k');
    let prompt = '';
    globalThis.fetch = vi.fn(async (_u: string, init: { body: string }) => {
      prompt = (JSON.parse(init.body) as { prompt: string }).prompt;
      return okJson({ data: [{ b64_json: PNG_B64 }] });
    }) as unknown as typeof fetch;
    const r = await resolvePhotoOrGenerate(bubble, persona, 'c1', 'seed', 'off', 1_754_600_000_000);
    expect(r?.ref.startsWith('idb:gen_')).toBe(true);
    expect(r?.caption).toBe('刚烤的饼干');
    // The prompt carries the bubble description AND the persona's style words.
    expect(prompt).toContain('刚烤的饼干');
    expect(prompt).toContain('美食');
  });

  it('generation fails → the old pool path answers (placeholder), zero errors', async () => {
    await saveImageProvider(CFG_SF);
    secrets.set(CFG_SF.keyAlias, 'k');
    globalThis.fetch = vi.fn(async () => {
      throw new Error('down');
    }) as unknown as typeof fetch;
    const r = await resolvePhotoOrGenerate(bubble, persona, 'c1', 'seed', 'off', 1);
    expect(r?.ref.startsWith('ph:')).toBe(true); // pre-J3 behavior, byte for byte
  });

  it('the engine hands over the TURN tier, not a literal (source scan)', () => {
    const src = readFileSync(resolve(__dirname, '../../src/ai/engine.ts'), 'utf8');
    // The call site passes the same `tier` local the router request uses.
    expect(src).toMatch(/resolvePhotoOrGenerate\([\s\S]{0,160}?,\s*tier,/);
    expect(src).not.toMatch(/resolvePhotoOrGenerate\([\s\S]{0,160}?,\s*'(off|ambiguous|full)'/);
  });
});

/* ------------------------------------------------------------------ */
/* Outlet 2: Moments 配图 (wiring-level; generation logic shared above) */
/* ------------------------------------------------------------------ */

describe('Moments 配图 wiring', () => {
  it('generateMomentPost gates on hasPoolMaterial and caps at ONE generated image', () => {
    const src = readFileSync(resolve(__dirname, '../../src/ai/moments-engine.ts'), 'utf8');
    expect(src).toContain('hasPoolMaterial(persona.imageTags)');
    expect(src).toMatch(/imageRefs:\s*\[ref\]/); // exactly one, never a batch
    expect(src).toContain('generateToLibrary');
  });
});

/* ------------------------------------------------------------------ */
/* Outlet 3: avatar swap on the moment_post tail                       */
/* ------------------------------------------------------------------ */

describe('AI 换头像（挂在 moment_post 尾部，无新 kind）', () => {
  const peer: ContactVM = { id: 'ai_a', type: 'ai', name: '林', avatarColor: '#000', avatarText: '林' };
  const persona = makePersona({ contactId: 'ai_a', core: '爱烘焙的邻家女孩' });

  function hooks() {
    const moments: MomentVM[] = [];
    const contacts: ContactVM[] = [];
    const h: MomentsHooks = {
      addMoment: async (m) => {
        moments.push(m);
      },
      applyLike: async () => {},
      addComment: async () => {},
      updateContact: async (c) => {
        contacts.push(c);
      },
      now: () => 1_754_600_000_000,
    };
    return { h, moments, contacts };
  }

  it('the gate is seeded and rare (deterministic, ~AVATAR_SWAP_RATE)', () => {
    expect(AVATAR_SWAP_RATE).toBeLessThanOrEqual(0.05);
    let hits = 0;
    for (let i = 0; i < 2000; i++) if (shouldSwapAvatar('ai_a', i * 97)) hits++;
    expect(hits / 2000).toBeGreaterThan(0.005);
    expect(hits / 2000).toBeLessThan(0.08);
    // Same inputs → same verdict, always.
    expect(shouldSwapAvatar('ai_a', 42)).toBe(shouldSwapAvatar('ai_a', 42));
  });

  it('swap: 512 avatar generated as kind "avatar", contact repointed, 换头像 moment posted', async () => {
    const stamp = [...Array(5000).keys()].map((i) => i * 131).find((t) => shouldSwapAvatar('ai_a', t));
    expect(stamp).toBeDefined();
    await saveImageProvider(CFG_SF);
    secrets.set(CFG_SF.keyAlias, 'k');
    let size = '';
    globalThis.fetch = vi.fn(async (_u: string, init: { body: string }) => {
      size = (JSON.parse(init.body) as { image_size: string }).image_size;
      return okJson({ data: [{ b64_json: PNG_B64 }] });
    }) as unknown as typeof fetch;

    const { h, moments, contacts } = hooks();
    await maybeAvatarSwap(persona, peer, [peer], () => persona, h, stamp!);

    expect(size).toBe('512x512');
    expect(contacts).toHaveLength(1);
    expect(contacts[0].avatarRef?.startsWith('idb:gen_')).toBe(true);
    const id = contacts[0].avatarRef!.slice(4);
    // kind 'avatar', NOT 'generated': hydration only eagerly materializes
    // avatars and eviction exempts them — any other kind degrades her face to
    // a placeholder tint after the next cold start.
    expect(media.get(id)).toMatchObject({ kind: 'avatar' });
    expect(moments).toHaveLength(1);
    expect(moments[0].text).toContain('换了个头像');
    expect(moments[0].imageRefs).toEqual([contacts[0].avatarRef]);
  });

  it('dice say no / no hook / not configured → nothing happens, silently', async () => {
    const stamp = [...Array(5000).keys()].map((i) => i * 131).find((t) => !shouldSwapAvatar('ai_a', t))!;
    const fetchSpy = vi.fn();
    globalThis.fetch = fetchSpy as unknown as typeof fetch;
    const a = hooks();
    await maybeAvatarSwap(persona, peer, [peer], () => persona, a.h, stamp);
    expect(a.moments).toHaveLength(0);

    // Dice yes but unconfigured: readiness gate answers first, zero network.
    const yes = [...Array(5000).keys()].map((i) => i * 131).find((t) => shouldSwapAvatar('ai_a', t))!;
    const b = hooks();
    await maybeAvatarSwap(persona, peer, [peer], () => persona, b.h, yes);
    expect(b.moments).toHaveLength(0);
    expect(b.contacts).toHaveLength(0);
    expect(fetchSpy).not.toHaveBeenCalled();
  });

  it('runMomentPost actually reaches the swap (写了没接线=没做)', () => {
    const src = readFileSync(resolve(__dirname, '../../src/ai/moments-service.ts'), 'utf8');
    const post = src.slice(src.indexOf('export async function runMomentPost'));
    expect(post.slice(0, post.indexOf('\n}'))).toContain('maybeAvatarSwap(');
  });
});

/* ------------------------------------------------------------------ */
/* Backfill purity                                                     */
/* ------------------------------------------------------------------ */

describe('离线回填的规划器碰不到生成（铁律 4/5 的纯度边界）', () => {
  it('simulate.ts imports neither the image transport nor gen-media', () => {
    // simulate() is THE pure planner: no LLM, no storage, no clock — and now,
    // no diffusion endpoint. Generation may only happen when a handler
    // MATERIALIZES a planned action (where it is a counted, caught, paid call).
    const src = readFileSync(resolve(__dirname, '../../src/ai/simulate.ts'), 'utf8');
    expect(src).not.toContain('llm/image');
    expect(src).not.toContain('gen-media');
    expect(src).not.toContain('generateImage');
  });
});
